### ISSUE TITLE
Do not create a new terminal on update

### ISSUE THREAD

**Issue by AlexanderPashuk** [mlshapiro/jupyterlab-flake8#16]
Hey there,

First of all, thanks for great extension!

I notice that extension creates a new terminal every time I update tab. It not looks like planned behavior :) 

![image](https://user-images.githubusercontent.com/3505985/53301481-69894680-3864-11e9-872a-f6afbc5919ae.png)

Maybe it is possible somehow to re-use already created terminals?

**Comment by AlexanderPashuk** [comment]
It looks like JupyterLab TerminalSession class currently doesn't have function to set custom name of session.

But they planned to add this feature in interface: https://github.com/jupyterlab/jupyterlab/issues/4393

So, I will be possible to set specific name to terminal, like 'F-8 TERMINAL', and re-use it instead of creation a new terminal.

**Comment by AlexanderPashuk** [comment]
Also, I created issue with question: https://github.com/jupyterlab/jupyterlab/issues/6031

**Comment by mlshapiro** [comment]
@AlexanderPashuk thank you for all the help and request to @jupyterlab. I have implemented a half-solution for this - there is still now way to set a specific name for a terminal, so I grab the name of the terminal opened by JupyterLab (i.e. `'2'`) the first time and stick it in the settings. The next time we'll try to connect to this terminal first, otherwise start a new one. Bit of a hack, but it may help your situation slightly.
