### ISSUE TITLE
Extension not producing output in files

### ISSUE THREAD

**Issue by valentinoli** [mlshapiro/jupyterlab-flake8#25]
I have tried many things to get this extension working in my JupyterLab environment, without luck. I am on Windows 10. I have already set the `conda_env` as the selected kernel's environment in the Advanced Settings Editor. The extension seems to be doing some work since it outputs something in the browser console but it doesn't output anything in `.py` files or notebooks. 

Versions:
jupyter lab      : 1.1.3

**Comment by andibuwono** [comment]
I my case, this extension is not working in my Windows 10 environments. Is due to incompatibility of newline and operator in powershell terminal.

I made a [fork for windows 10](https://github.com/andibuwono/jupyterlab-flake8/commit/cf314e47b41e04cae84dfebcfdfcb75611293f56)

which involve in:
- change newline from "\n" to "`n"
- change && and || operator for power shell compatibility
- some marking change to exclude unused character

but yet to make the fork working cross platform.

Hope its helps.

**Comment by mlshapiro** [comment]
@andibuwono thank you for the powershell edits. I included them in ba9714c8205b31b692a17b912b18ac8c462d17c8 with a switch for the OS. I'm no 100% this will work as expected, but try extension 0.4 and see if it works cross platform.

I confirm it works as expected on the unix side.

**Comment by andibuwono** [comment]
0.4 seems fine for windows now. thanks

**Comment by valentinoli** [comment]
Thank you for looking into this. 0.4 is not working on my side though. I get this in the console

```
jupyterlab-flake8: loaded settings {"conda_env":"ada","logging":true,"terminal_name":"","toggled":true,"highlight_color":"var(--jp-warn-color3)","gutter_color":"var(--jp-error-color0)","term_timeout":5000}

jupyterlab-flake8: flake8 is already running onActiveCellChanged
```

Some output is shown in the Terminal window but no output appearing in the cells.

**Comment by valentinoli** [comment]
It works! Thank you!
