### ISSUE TITLE
Does jupyterlab-flake8 work in a text editor in JupyterLab? 

### ISSUE THREAD

**Issue by dclong** [mlshapiro/jupyterlab-flake8#3]
Does jupyterlab-flake8 work in a text editor in JupyterLab?

**Comment by mlshapiro** [comment]
it does not currently. it would be fairly easy to add, though the way that I check the notebooks is somewhat particular since the notebooks present a fairly different linting circumstance than a python file.

I think it would be very useful to have a piece of this plugin or another extension that used `flake8` or ( or better yet `pylint`) to lint single files and full modules. Files and modules are a slightly different use case than the notebook linting, which is generally not part of a module or larger ecosystem (its more like spell checking). 

If I have time I will extend this extension to work in the text editor. Please feel free to contribute this change if you have the time!

**Comment by JeremieGuez** [comment]
Hey,
It would be a wonderfull feature. How can we help you to develop it ?

**Comment by JeremieGuez** [comment]
thanks, I will try to find time to implement it.

**Comment by haeusser** [comment]
upvote 👍

**Comment by jbusecke** [comment]
upvote 👍

**Comment by JeremieGuez** [comment]
upvote 👍

**Comment by JeremieGuez** [comment]
@mlshapiro I tried to fix it but make some mistake. Can you try to push a proto and i will try to continue ?

**Comment by mlshapiro** [comment]
i figured out how to implement, coming shortly

**Comment by mlshapiro** [comment]
implemented in 97b7c3c01dd0fcb6bad9d980ef7071ef18ca6a8c, released in 0.2.0

**Comment by JeremieGuez** [comment]
Such a good news !!

I try to test but it's not working... :( Any tips? 
<img width="364" alt="capture d ecran 2018-08-01 a 12 28 16" src="https://user-images.githubusercontent.com/15033641/43516644-7eb8415e-9586-11e8-96fd-09f3e29b4952.png">

**Comment by mlshapiro** [comment]
make sure you have the latest version of the plugin installed:

```
$ jupyter labextension list
```
and make sure it reads

```
jupyterlab-flake8
        jupyterlab-flake8 v0.2.0  enabled  OK
```

it also may be due to the fact that jupyter is not seeing the default language as python.  If you turn on the browser logging and look at the browser console do you see the message:

```
not python default lang
```

i'll push a small update that also checks the file for .py extension.

**Comment by mlshapiro** [comment]
pushed 0.2.1 looking for .py extensions as well

**Comment by JeremieGuez** [comment]
```
"jupyterlab-flake8@0.2.2" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab              Extension        Package
>=0.16.3 <0.17.0        >=0.17.2 <0.18.0 @jupyterlab/application
>=0.16.4 <0.17.0        >=0.17.2 <0.18.0 @jupyterlab/apputils
>=1.1.3 <2.0.0          >=2.0.2 <3.0.0   @jupyterlab/coreutils
>=0.16.3 <0.17.0        >=0.17.2 <0.18.0 @jupyterlab/fileeditor
>=0.16.3 <0.17.0        >=0.17.2 <0.18.0 @jupyterlab/notebook
>=0.16.3 <0.17.0        >=0.17.2 <0.18.0 @jupyterlab/terminal
```

I tried to npm each extension, but still not working
